---
  - name: create a directory for certificates
    file:
      path: /root/certs
      state: directory
      mode: '0755'
      
  - name: Copy CA certificates to the target host
    copy:
      src: ../files/*
      dest: /root/certs/

  - name: Move CA certificate to /etc/ssl/certs/
    become: true
    command: cp /root/certs/CA* /etc/ssl/certs/*

  - name: Update CA certificate store
    become: true
    command: update-ca-trust

  - name: check certificate validity
    become: true
    shell: |
        validityCA1=$(openssl x509 -in /etc/ssl/certs/CA1.crt  -text -noout --dates | grep notAfter)
        validityCA2=$(openssl x509 -in /etc/ssl/certs/CA2.crt  -text -noout --dates | grep notAfter)
        validityCA2=$(openssl x509 -in /etc/ssl/certs/CA3.crt  -text -noout --dates | grep notAfter)
        echo certificate CA1 is valid till $validityCA1
        echo certificate CA2 is valid till $validityCA2
        echo certificate CA3 is valid till $validityCA3
        
